@echo off
echo Building Java backend...
call mvn clean package

echo Starting Java backend with optimized memory settings...
start /b java -Xmx1536m -Xms512m -XX:+UseG1GC -jar target\p2p-1.0-SNAPSHOT.jar

echo Waiting for backend to start...
timeout /t 5

echo Checking if node_modules exists...
if not exist ui\node_modules (
    echo Installing frontend dependencies...
    cd ui && npm install && cd ..
)

echo Starting frontend...
cd ui && npm start

echo Stopping backend...
taskkill /f /im java.exe